server: 
  port: 9004
spring: 
  application:  
    name: huahua-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.2.17.129:3306/huahua_article?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
#redis
  redis:
    host: 10.2.17.129
    port: 6379

#mongodb配置
  data:
    mongodb:
      host: 39.97.117.83
      port: 27017
      database: recruitdb