server:
  port: 9011
spring:
  application:
    name: huahua-manager
#jwt.config
jwt:
  config:
    key: huahuaCommunity
#注册到eureka服务
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/ #设置当前访问的路径
  instance:
    prefer-ip-address: true
zuul:
  routes:
    huahua-base: #基础
      path: /base/**  #配置请求URL的请求规则
      serviceId: huahua-base  #指定Eureka注册中心中的服务id
