server:
  port: 9006
spring:
  application:
    name: huahua-spit
    #mongo db
  data:
    mongodb:
      host: 39.97.117.83
      database: spitdb
      port: 27017

  redis:
    host: 39.97.117.83
    port: 6379
    password: zhangyy

#  data:
#    mongodb:
#      host: 39.97.117.83
#      database: spitdb
#      port: 27017