server:
  port: 12000
spring:
  application:
    name: huahua-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wclmayun/huahua.git
  rabbitmq:
    host: 10.2.17.130
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh